import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Clock, MapPin, Users } from "lucide-react";

import { Card } from "@/components/shared/Card";
import { DataTable, type Column } from "@/components/shared/DataTable";
import { PageHeader } from "@/components/shared/PageHeader";
import { SeverityBadge, SeverityLegend } from "@/components/shared/SeverityBadge";
import { StatTile } from "@/components/shared/StatTile";
import { StatusDot } from "@/components/shared/StatusDot";
import {
  DISTRICT_IMPACTS,
  LAST_ISSUE_TIME,
  MODELS,
  WARNING_SIGNALS,
  type DistrictImpact,
} from "@/lib/mock";

const columns: Column<DistrictImpact>[] = [
  {
    key: "district",
    header: "District",
    render: (row) => (
      <div>
        <p className="font-medium text-navy-900">{row.district}</p>
        <p className="text-xs text-navy-500">{row.division}</p>
      </div>
    ),
  },
  {
    key: "severity",
    header: "Impact level",
    render: (row) => <SeverityBadge level={row.severity} />,
  },
  {
    key: "people",
    header: "People at risk",
    numeric: true,
    render: (row) => (row.peopleAtRisk ? `≈ ${row.peopleAtRisk.toLocaleString()}` : "—"),
  },
  {
    key: "unions",
    header: "Unions",
    numeric: true,
    render: (row) => (row.unionsAffected || "—"),
  },
  {
    key: "lead",
    header: "Lead time",
    numeric: true,
    render: (row) => `${row.leadTimeHours} h`,
  },
];

export default function DashboardPage() {
  const totalAtRisk = DISTRICT_IMPACTS.reduce((sum, row) => sum + row.peopleAtRisk, 0);
  const districtsAtRisk = DISTRICT_IMPACTS.filter((row) =>
    ["moderate", "severe", "extreme"].includes(row.severity),
  ).length;

  return (
    <>
      <PageHeader
        title="Dashboard"
        description="The current impact picture across Bangladesh, drawn from the latest model runs."
        meta={
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-xs text-navy-500">
            <span className="inline-flex items-center gap-1.5">
              <Clock className="size-3.5" />
              Latest forecast issued {LAST_ISSUE_TIME}
            </span>
            <SeverityLegend />
          </div>
        }
      />

      <div className="space-y-6 p-6">
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <StatTile
            label="People at risk (72 h)"
            value={`≈ ${totalAtRisk.toLocaleString()}`}
            context="Across all districts at advisory level or above"
            icon={<Users className="size-4" />}
          />
          <StatTile
            label="Districts at level 3+"
            value={districtsAtRisk}
            context="Moderate, severe or extreme impact expected"
            icon={<MapPin className="size-4" />}
          />
          <StatTile
            label="Active warning signals"
            value={WARNING_SIGNALS.length}
            context="Generated by the AI analysis layer"
          />
          <StatTile
            label="Models reporting"
            value={`${MODELS.filter((m) => m.status === "healthy").length} / ${MODELS.length}`}
            context="Services responding to health checks"
          />
        </section>

        <div className="grid gap-6 xl:grid-cols-3">
          <Card
            title="Impact by district"
            subtitle="Ranked by people at risk within the next 72 hours"
            className="xl:col-span-2"
            bodyClassName="p-0"
            action={
              <Link
                to="/pre-crisis"
                className="inline-flex items-center gap-1 text-xs font-medium text-green-700 hover:underline"
              >
                Open targeting dashboard <ArrowUpRight className="size-3.5" />
              </Link>
            }
          >
            <DataTable columns={columns} rows={DISTRICT_IMPACTS} rowKey={(row) => row.id} />
          </Card>

          <div className="space-y-6">
            <Card
              title="Warning signals"
              subtitle="Plain-language signals from model output"
              bodyClassName="p-0"
              action={
                <Link
                  to="/early-warning"
                  className="inline-flex items-center gap-1 text-xs font-medium text-green-700 hover:underline"
                >
                  All signals <ArrowUpRight className="size-3.5" />
                </Link>
              }
            >
              <ul className="divide-y divide-navy-200">
                {WARNING_SIGNALS.map((signal) => (
                  <li key={signal.id} className="px-6 py-4">
                    <div className="flex items-start justify-between gap-3">
                      <p className="text-sm font-medium leading-snug text-navy-900">
                        {signal.headline}
                      </p>
                      <SeverityBadge level={signal.severity} className="shrink-0" />
                    </div>
                    <p className="mt-1.5 text-xs text-navy-500">
                      {signal.area} · {signal.issuedAt}
                    </p>
                    <p className="mt-1 text-caption">{signal.source}</p>
                  </li>
                ))}
              </ul>
            </Card>

            <Card
              title="Model status"
              subtitle="Live health of each registered service"
              bodyClassName="p-0"
              action={
                <Link
                  to="/models"
                  className="inline-flex items-center gap-1 text-xs font-medium text-green-700 hover:underline"
                >
                  All models <ArrowUpRight className="size-3.5" />
                </Link>
              }
            >
              <ul className="divide-y divide-navy-200">
                {MODELS.map((model) => (
                  <li key={model.id}>
                    <Link
                      to={model.to}
                      className="flex items-center justify-between gap-3 px-6 py-3 hover:bg-green-100"
                    >
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium text-navy-900">
                          {model.shortName}{" "}
                          <span className="font-normal text-navy-500">{model.version}</span>
                        </p>
                        <p className="text-xs text-navy-500">{model.module}</p>
                      </div>
                      <StatusDot status={model.status} />
                    </Link>
                  </li>
                ))}
              </ul>
            </Card>
          </div>
        </div>

        <p className="text-caption">
          Figures shown are demonstration data except where a model reports live. Every impact
          number in production carries the model, version and issue time behind it.
        </p>
      </div>
    </>
  );
}
